"""Unscented Kalman filter on SO(3) (USQUE-style error-state formulation).

The textbook UKF cannot be applied to quaternions directly: sigma points
generated by adding columns of √P to a quaternion leave the unit sphere, and
their barycentric mean is not a rotation average. The standard resolution
(Crassidis & Markley's USQUE) runs the unscented transform on a **3D
attitude-error state** and retracts onto the quaternion manifold:

- Sigma points: ``qᵢ = q̂ ⊗ Exp(δχᵢ)`` with ``δχᵢ`` the scaled columns of
  ``√((n+λ)P)`` — the right/local tangent perturbation used everywhere in
  qnav.
- Propagation: each sigma quaternion advances with the gyro exponential map;
  the predicted mean is the **Markley quaternion mean** of the propagated
  set (eigenvector method — not a normalized arithmetic mean), and the
  predicted covariance is rebuilt from ``Log(q̄⁻¹ ⊗ qᵢ)``.
- Measurement: any body-frame direction observation
  ``z = R(q)ᵀ v_nav + n``; the unscented transform maps sigma attitudes
  through the exact measurement function (no Jacobian linearization — the
  advantage over the ESKF for large attitude uncertainty).
- Update: standard UT cross-covariance gain; the correction is injected via
  ``q ← q̄ ⊗ Exp(δ)``.

The filter state is attitude-only (3 error dimensions); gyro bias should be
handled upstream (e.g. ``qnav.calibration.gyro_bias``) or with the ESKF. The
honest trade-off versus the ESKF: ~7× the per-step cost, no linearization
error in the update — relevant when initial uncertainty exceeds ~20°.

References: Crassidis & Markley, "Unscented filtering for spacecraft
attitude estimation", JGCD 26(4), 2003; Wan & van der Merwe (UT weights).
"""

from __future__ import annotations

import numpy as np

from qnav.attitude import quaternion as quat
from qnav.filters.base import AttitudeFilter

__all__ = ["UkfAttitude"]


class UkfAttitude(AttitudeFilter):
    """Error-state unscented attitude filter (3D tangent, direction updates).

    Parameters
    ----------
    gyro_noise_density:
        σ_g [rad/s/√Hz]; discrete Qd = σ_g²·dt·I.
    P0:
        Initial 3×3 attitude-error covariance (default (0.3 rad)²·I).
    alpha, beta, kappa:
        UT scaling (Wan-van der Merwe). Defaults: 1e-1, 2.0, 0.0; α sets the
        sigma-point spread, β=2 is optimal for Gaussian priors.
    """

    def __init__(
        self,
        gyro_noise_density: float,
        P0: np.ndarray | None = None,
        alpha: float = 0.1,
        beta: float = 2.0,
        kappa: float = 0.0,
        q0=None,
        nav_frame: str = "NED",
    ) -> None:
        super().__init__(q0=q0, nav_frame=nav_frame)
        self.sigma_g = float(gyro_noise_density)
        self.P = (0.3**2) * np.eye(3) if P0 is None else np.asarray(P0, dtype=float).copy()
        if self.P.shape != (3, 3):
            raise ValueError("P0 must be 3×3 over the attitude tangent")
        n = 3
        lam = alpha**2 * (n + kappa) - n
        self._gamma = np.sqrt(n + lam)
        self._wm = np.full(2 * n + 1, 1.0 / (2.0 * (n + lam)))
        self._wc = self._wm.copy()
        self._wm[0] = lam / (n + lam)
        self._wc[0] = lam / (n + lam) + (1.0 - alpha**2 + beta)

    # -- sigma-point machinery ----------------------------------------------
    def _clamp_cov(self) -> None:
        """Symmetrize and clamp P's spectrum to [1e-14, (π/2)²].

        The upper clamp keeps sigma-point tangents inside the injectivity
        radius of Exp (perturbations beyond π alias back); the lower keeps
        the Cholesky factorization alive after UT subtraction round-off.
        """
        self.P = 0.5 * (self.P + self.P.T)
        w, V = np.linalg.eigh(self.P)
        w = np.clip(w, 1e-14, (np.pi / 2.0) ** 2)
        self.P = (V * w) @ V.T

    def _sigma_quaternions(self) -> np.ndarray:
        """(7, 4) sigma attitudes ``q̂ ⊗ Exp(±γ·√P columns)``."""
        self._clamp_cov()
        L = np.linalg.cholesky(self.P)
        deltas = np.vstack([np.zeros(3), self._gamma * L.T, -self._gamma * L.T])
        return quat.mul(self.q, quat.exp(deltas))

    def _mean_and_tangents(self, qs: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """Markley mean + right-tangent residuals of a sigma set."""
        q_mean = quat.mean(qs, self._wm)
        d = quat.log(quat.mul(quat.conjugate(q_mean), qs))
        return q_mean, d

    # -- prediction ----------------------------------------------------------
    def _predict(self, omega_body: np.ndarray, dt: float) -> np.ndarray:
        """Unscented propagation through the gyro exponential map."""
        qs = self._sigma_quaternions()
        dq = quat.exp(np.asarray(omega_body, dtype=float) * dt)
        qs = quat.normalize(quat.mul(qs, dq))
        self.q, d = self._mean_and_tangents(qs)
        self.P = (d.T * self._wc) @ d + (self.sigma_g**2 * dt) * np.eye(3)
        return self.q

    # -- measurement update --------------------------------------------------
    def update_direction(
        self, v_nav: np.ndarray, v_body_meas: np.ndarray, sigma: float
    ) -> np.ndarray:
        """Fuse a unit-direction observation through the unscented transform.

        ``v_nav``: known nav-frame direction (any norm); ``v_body_meas``:
        measured body direction (any norm); ``sigma``: per-axis noise std of
        the unit measurement. Returns the innovation for monitoring.
        """
        vn = np.asarray(v_nav, dtype=float)
        vn = vn / np.linalg.norm(vn)
        vb = np.asarray(v_body_meas, dtype=float)
        nb = np.linalg.norm(vb)
        if nb < 1e-12:
            raise ValueError("zero-norm body measurement")
        vb = vb / nb

        qs = self._sigma_quaternions()
        q_mean, d = self._mean_and_tangents(qs)
        Z = quat.rotate_frame(qs, vn)              # exact measurement function
        z_hat = self._wm @ Z
        dz = Z - z_hat
        S = (dz.T * self._wc) @ dz + sigma**2 * np.eye(3)
        C = (d.T * self._wc) @ dz                  # 3×3 cross-covariance
        K = np.linalg.solve(S.T, C.T).T

        innov = vb - z_hat
        delta = K @ innov
        self.q = quat.normalize(quat.mul(q_mean, quat.exp(delta)))
        self.P = self.P - K @ S @ K.T
        self._clamp_cov()
        return innov

    @property
    def attitude_std(self) -> np.ndarray:
        """Per-axis attitude error std [rad] (right/local tangent)."""
        return np.sqrt(np.clip(np.diag(self.P), 0.0, None))
